
modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="silverwolfsbuildingblocks" #mandatory

version="1.16.3_1.0.3" #mandatory

displayName="Silverwolf's Building Blocks" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/silverwolfs-building-blocks" #optional

logoFile="examplemod.png" #optional

credits="Thanks to Sekelsta" #optional

authors="Silverwolf" #optional

description='''
Adds more building blocks
'''

[[dependencies.silverwolfsbuildingblocks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34.0.9,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
